In [ ]:
# numpy ka backend C language me likha gaya he

In [ ]:
# 1d array
import numpy as np
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [ ]:
# 2d arry :-
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [ ]:
# 3d array
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr.shape)

(2, 3)


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr.size)

6


In [ ]:
arr.ndim # number of dimantion

2

In [ ]:
marks=[50,60,70,80]
marks*5

[50,
 60,
 70,
 80,
 50,
 60,
 70,
 80,
 50,
 60,
 70,
 80,
 50,
 60,
 70,
 80,
 50,
 60,
 70,
 80]

In [ ]:
marks=np.array([50,60,70,80])
marks*2
# vectorized operations (whithout loop ka code)
# performing one operation on a all elements togrther without writhing and using loops

array([100, 120, 140, 160])

In [ ]:
import time()
start=time.time()
lst= list(range(1000000))
new=[]
for i in lat:
  new.append(i+5)

end=time.time()
print(end.start)

In [ ]:
import time()
start=time.time()
lst= np.arange(1000000)
arr=arr+5
end=time.time()
print(end.start)

In [ ]:
# array types:-
# 2) np.arange():- crate an       np.arrange(atart,stop,step)

arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [ ]:
# 3) np.linespace() :- do number ke bich distance genrate karta he
arr=np.linspace(1,5,100)
print(arr)

[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4.35353535
 4.39393939 4.43434343 4.47474747 4.51515152 4.55555556 4.595959

In [ ]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(5)

array([0.46638647, 0.61814239, 0.14937672, 0.569263  , 0.72866928])

In [ ]:
np.random.randint(1,100,5)

array([18,  9,  3, 98, 95])

In [ ]:
# reshape() :- changes the shape of ann array without changing its data
arr=np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# random.choice()

In [ ]:
# indexing

In [ ]:
import numpy as np
arr= np.array([60,75,90,80,75])
print(arr)
print(arr[0])

[60 75 90 80 75]
60


In [ ]:
marks=np.array([[60,70,80],[60,75,95]])
marks

array([[60, 70, 80],
       [60, 75, 95]])

In [ ]:
print(marks[1,2])

95


In [ ]:
print(marks[1,0])

60


In [ ]:
# slicing :- it is a prosess of assesing data continuasly

In [ ]:
import numpy as np
arr= np.array([60,75,90,80,75])
print(arr[1:4]) #exckude=n-1

[75 90 80]


In [ ]:
marks=np.array([[60,70,80],[60,75,95],[88,92,78]])

In [ ]:
print(marks[0,:])
# 0 meance 1st row and 1 miance all colums

[60 70 80]


In [ ]:
print(marks[1,:])

[60 75 95]


In [ ]:
print(marks[:,1])

[70 75 92]


In [ ]:
print(marks[:,-1])

[80 95 78]


In [ ]:
print(marks[:,0:2])

[[60 70]
 [60 75]
 [88 92]]


In [ ]:
print(marks[1:,:])

[[60 75 95]
 [88 92 78]]


In [ ]:
marks[1,:]

array([60, 75, 95])

In [ ]:
marks[:,2]

array([80, 95, 78])

In [ ]:
marks[2,:]

array([88, 92, 78])

In [ ]:
marks[:,:]

array([[60, 70, 80],
       [60, 75, 95],
       [88, 92, 78]])

In [ ]:
marks[1:3,:]

array([[60, 75, 95],
       [88, 92, 78]])

In [ ]:
marks[:,1:3]

array([[70, 80],
       [75, 95],
       [92, 78]])

In [ ]:
marks[1:3,1:3]

array([[75, 95],
       [92, 78]])

In [ ]:
# array operations :-
marks = np.array([50,60,70,80])
print(marks+5)
print(marks-5)
print(marks*5)
print(marks/5)
print(marks**5)
print(marks%5)

[55 65 75 85]
[45 55 65 75]
[250 300 350 400]
[10. 12. 14. 16.]
[ 312500000  777600000 1680700000 3276800000]
[0 0 0 0]


In [ ]:
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 60  80 100 120]
[-40 -40 -40 -40]
[ 500 1200 2100 3200]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
# universal function

marks = np.array([80,70,90,60,100])
print(np.max(marks))
print(np.min(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.var(marks))
print(np.sum(marks))
print(np.prod(marks))
print(np.sqrt(marks))

100
60
80.0
80.0
14.142135623730951
200.0
400
3024000000
[ 8.94427191  8.36660027  9.48683298  7.74596669 10.        ]


In [ ]:
# reshap, fatten, ravel,